//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Complex
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public int ID { get; set; }
        public int HouseID { get; set; }
        public int NumOfFlat { get; set; }
        public decimal Area { get; set; }
        public int CountOfRooms { get; set; }
        public int Porch { get; set; }
        public int Floor { get; set; }
        public int SaleStatusID { get; set; }
        public int AddedValue { get; set; }
        public int CostOfBuilding { get; set; }
        public bool VisibleStatus { get; set; }
    
        public virtual House House { get; set; }
        public virtual SaleStatus SaleStatus { get; set; }

        public virtual string Address => String.Format("ул.{0}, д.{1}, кв.{2}", House.Street, House.NumberOfHouse, NumOfFlat);
    }
}
